import java.util.*;
import java.awt.event.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucas
 */
public class interfaceJogo extends javax.swing.JFrame {

    /**
     * Creates new form interfaceJogo
     */
    public interfaceJogo() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbLetras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtChutar = new javax.swing.JTextField();
        btnChutar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtForca = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jlbTema = new javax.swing.JLabel();


        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setBounds(550, 200, 382, 361);
        this.setResizable(false);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("jogo da forca");

        jlbLetras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        
        int j = palavra.getQtd_letras();
        for(int i = 0;i<j;i++){
            letras = letras.append("_");
        }
        jlbLetras.setText(letras.toString());

        jLabel3.setText("chutes");

        txtChutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChutarActionPerformed(evt);
            }
        });

        btnChutar.setText("chutar");
        btnChutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChutarActionPerformed(evt);
            }
        });

        txtForca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtForca.setFocusable(false);
        txtForca.setText("----------------\n"+
        "|                      |\n"+
        "|\n"+
        "|\n"+
        "|\n"+
        "|\n"+
        "|");
        jScrollPane4.setViewportView(txtForca);

        jTextPane1.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jLabel4.setText("tema:");

        jlbTema.setText(palavra.getTema());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtChutar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChutar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jlbTema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChutar))
                .addGap(39, 39, 39))
        );

        this.setTitle("jogo da forca");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtChutar.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e1) {
                if(e1.getKeyCode() == KeyEvent.VK_ENTER) { 
                    btnChutarActionPerformed(null);
                }
            }
        });

        pack();
    }// </editor-fold>                        

    private void txtChutarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnChutarActionPerformed(java.awt.event.ActionEvent evt) {
        if(letrasChutadas.contains(txtChutar.getText())){
            JOptionPane.showMessageDialog(null,"A letra escolhida já foi chutada","Atenção",1);
        }else{
            int j = palavra.getQtd_letras();
            int i;
            char chute = txtChutar.getText().charAt(0);
            letrasChutadas = letrasChutadas.concat(chute+"\n");
            if(palavra.temLetra(chute)){

                for(i = 0;i<j;i++){
                    if(palavra.getPalavra().charAt(i) ==  chute){
                        letras.setCharAt(i, chute);  
                    }   
                }
                String Sletras = letras.toString();
                jlbLetras.setText(Sletras);
            }else{
                erros++;
            }
            for(i = 0;i<j;i++){
                if(letras.charAt(i) == '_'){
                    barras = i;
                }
            }
            if(barras == -1){
                JOptionPane.showMessageDialog(null,"Você ganhou!","Atenção",1);
            }
            barras = -1;
        }
        switch (erros) {
            case 1:
                txtForca.setText("----------------\n"+
                "|                      |\n"+
                "|                      O\n"+
                "|\n"+
                "|\n"+
                "|\n"+
                "|");
                break;
        
            case 2:
                txtForca.setText("----------------\n"+
                "|                      |\n"+
                "|                      O\n"+
                "|                       |\n"+
                "|\n"+
                "|\n"+
                "|");
                break;
            case 3:
                txtForca.setText("----------------\n"+
                "|                      |\n"+
                "|                      O\n"+
                "|                      /|\n"+
                "|\n"+
                "|\n"+
                "|");
                break;
            case 4:
                txtForca.setText("----------------\n"+
                "|                      |\n"+
                "|                      O\n"+
                "|                      /|\\ \n"+
                "|\n"+
                "|\n"+
                "|");
                break;
            case 5:
                txtForca.setText("----------------\n"+
                "|                      |\n"+
                "|                      O\n"+
                "|                      /|\\ \n"+
                "|                       /\n"+
                "|\n"+
                "|");
                break;
            case 6:
                txtForca.setText("----------------\n"+
                "|                      |\n"+
                "|                      O\n"+
                "|                      /|\\ \n"+
                "|                       /\\ \n"+
                "|\n"+
                "|");
                if(true){
                    JOptionPane.showMessageDialog(null,"Você perdeu!","Atenção",1);
                }
                jlbLetras.setText(palavra.getPalavra());
                break;
            default:
        }
        txtChutar.setText("");
        jTextPane1.setText(letrasChutadas);
    }                                         


    /**
     * @param args the command line arguments
     */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

        /* Create and display the form */

            public void run() {
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //
                new interfaceJogo().setVisible(true);
            }

    // Variables declaration - do not modify                 
    String letrasChutadas = "";
    private javax.swing.JButton btnChutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbLetras;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jlbTema;
    private javax.swing.JTextField txtChutar;
    private javax.swing.JTextPane txtForca;
    private Nivel nivel = new Nivel();
    private Armazenamento nivel1 = new Armazenamento("nivel1.dat");
    Random gerador = new Random();
    Palavra palavra = (Palavra)nivel1.obter(gerador.nextInt(19));
    int t = palavra.qtd_letras;
    StringBuilder letras = new StringBuilder("");
    int erros = 0;
    int barras = -1;
    // End of variables declaration                   
}
